### ISSUE TITLE
CardManager 클래스의 GetCard 함수 및 GetCardWithCombination 함수 작성

### ISSUE THREAD

**Issue by yejun614** [Human-Interpreter/Larva#11]
## 설명
플레이어가 서버에게 카드를 요청했을 때 해당 플레이어에게 적절한 카드를 랜덤으로 생성하여 전달해 주는 코드 작성

## TODO
TODO 리스트를 필요에 따라 수정해서 사용하세요.
- [ ] CardManager.GetCard 함수 내용 작성
- [ ] CardManager.GetCardWithCombination 함수 내용 작성
- [ ] Player.TargetGetCardResponse 함수 내용 작성

**Comment by yejun614** [comment]
해당 이슈는 #29 이슈로 병합 되었습니다.
