### ISSUE TITLE
Readme 파일 추가

### ISSUE THREAD

**Issue by yejun614** [Human-Interpreter/Larva#2]
## TODO
- [x] 프로젝트 설명 추가
- [x] 프로젝트 문서 링크 추가
- [x] 프로젝트 일정 추가
