### ISSUE TITLE
카드 클래스 테스트 코드 추가

### ISSUE THREAD

**Issue by yejun614** [Human-Interpreter/Larva#23]
## Issues
- #19

## 설명
- 카드 클래스를 테스트 할 수 있는 UI 추가

## TODO
- [x] GetPlayer 명령어 추가
- [x] ActiveCard 매서드 분리
- [x] TestCard 명령어 추가
