### ISSUE TITLE
Gameplay 관련 스크립트 추가

### ISSUE THREAD

**Issue by yejun614** [Human-Interpreter/Larva#6]
## TODO (Class)
- [x] GameManager Class 작성
- [x] VoteManager Class 작성
- [x] CardManager Class 작성
- [x] Player Class 작성
- [x] PlayerData Class 작성
- [x] CardData Class 작성
- [x] CardIdentity Class 작성

## TODO (추가)
- [x] GameState Enum 작성
- [x] GamePhase Enum 작성
- [x] TeamType Enum 작성
- [x] 이벤트 작성

## Reference
- [Gameplay](https://drive.google.com/file/d/1fWhHmCD9OqXDTTfssVQDJoa6Qcj4q0lC/view?usp=sharing)
